apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: "xps-talos-l2-policy"
spec:
  serviceSelector: {}
  nodeSelector:
    matchExpressions:
      - key: "kubernetes.io/os"
        operator: In
        values:
          - linux
  interfaces:
    - ^ens18$ # This matches your exact Proxmox virtual interface
  externalIPs: true
  loadBalancerIPs: true
