[controllers]
k3s-ctlr-01 ansible_host=10.3.160.101
k3s-ctlr-02 ansible_host=10.3.160.102
k3s-ctlr-03 ansible_host=10.3.160.103

[workers]
k3s-worker-01 ansible_host=10.3.160.104
k3s-worker-02 ansible_host=10.3.160.105

[k3s_cluster:children]
controllers
workers

[all:vars]
ansible_user=xpsadmin  # Change to your cloud-init username
ansible_ssh_private_key_file=~/.ssh/id_rsa
k3s_registration_address=10.3.160.100  # This is the Kube-VIP address
